### ISSUE TITLE
UnityAds not loading on Android

### ISSUE THREAD

**Issue by primozv** [cranberrygame/cordova-plugin-ad-unityads#1]
HI,
It seems ads are not showing anymore on Android. I'm using cocoon.io to build my project and a few days ago, ads stopped to show on Android, latest version is taken from github.
In tested a build where older version of plugin was used and it still works fine, I event tried replacing the  javascript code with the latest code and it also work fine. It doesn't work when new build is made where latest version is taken from the repository. It stopped working after a build last week (around Wednesday, 11.11. ), but just on android, it seems the ads are never loaded and loadedRewardedVideoAd() returns false.

I saw there were some changes made, is there a way to pull out earlier version?

BR
Primoz

**Comment by cranberrygame** [comment]
@primozv 

Fixed the issue.
Thanks

**Comment by sabrielle6** [comment]
I'm getting this now too.
